CREATE DATABASE COVID_RESOURCE_MANAGEMENT ;
USE COVID_RESOURCE_MANAGEMENT;

CREATE TABLE HOSPITAL
(REG_ID INT PRIMARY KEY,NAME VARCHAR(60) NOT NULL,OWNERSHIP CHAR(15),LOCATION VARCHAR(50),CITY CHAR(10) ,CONTACT NUMERIC(10) UNIQUE,
CHECK (CITY IN ("Delhi","Kolkata","Mumbai","Bangalore")));

CREATE TABLE RESOURCES (REG_ID INT,OXYGEN INT DEFAULT 0,REMDESIVIR INT DEFAULT 0,VENTILATOR INT DEFAULT 0,BEDS INT DEFAULT 0,
FOREIGN KEY (REG_ID) REFERENCES HOSPITAL(REG_ID));

CREATE TABLE BLOOD_BANK (REG_ID INT , BLOOD_GROUP CHAR(15) DEFAULT "NOT AVAILABLE",
FOREIGN KEY (REG_ID) REFERENCES HOSPITAL(REG_ID));

CREATE TABLE VACCINATION (REG_ID INT,DOSE_TYPE CHAR(15) DEFAULT "NOT AVAILABLE",
FOREIGN KEY (REG_ID) REFERENCES HOSPITAL(REG_ID));

CREATE TABLE COVID_STATUS (REG_ID INT,ACTIVE_CASES INT NOT NULL,MORTALITY_RATE FLOAT,RECOVERED INT NOT NULL,
FOREIGN KEY (REG_ID) REFERENCES HOSPITAL(REG_ID));
