USE COVID_RESOURCE_MANAGEMENT;
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 1, "Dharamshila Narayana Superspeciality Hospital", "Private", "Dharamshila Marg ", "Delhi", 8067506818);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 2, "Manipal Hospital", "Private", "Dwarka Sector 6 ", "Delhi", 7947058365);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 3, "Fortis Hospital", "Private", "B-22, Noida Sector 62", "Delhi", 7947182042);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 4, "Bhagat Hospital", "Private", "D-2/48-49 Janakpuri ", "Delhi", 7947211746);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 5, "Mahindru Hospital", "Private", "Uttam Nagar ", "Delhi", 7947220203);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 6, "Max Super Speciality Hospital", "Private", "FC-50 Street Number", "Delhi", 7947073033);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 7, "Aavaam Hospital", "Private", "Kalicharan Market Kasna ", "Delhi", 7947084119);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 8, "Indraprastha Apollo Hospitals", "Private", "Delhi Mathura Road", "Delhi", 7947072799);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 9, "Columbia Asia Hospital", "Private", "F Block Rezangla Road", "Delhi", 7940705624);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 10, "Sarvodaya Hospitals & Research Centre", "Private", "YMCA Road Faridabad", "Delhi", 7947213094);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 11, "Adarsh Hospital", "Private", "Plot E 40 Jain Mandir", "Delhi", 7947225146);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 12, "Maharaja Agrasen Hospital", "Private", "Main Road Dwarka", "Delhi", 7947219801);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 13, "Ssb Heart And Multispecialty Hospital", "Private", "Plot - 67 Faridabad", "Delhi", 7947187273);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 14, "Mata Roop Rani Maggo Hospital", "Private", "Om Vihar Uttam Nagar", "Delhi", 7947071616);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 15, "Rashi Medical Centre", "Private", "Palam Road Dabri", "Delhi", 7947220145);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 16, "Mahajan Hospital", "Private", "Milap Nagar", "Delhi", 7947063690);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 17, "Gupta Hospital & Maternity Centre", "Private", "Khora Colony Sector 62", "Delhi", 7947208072);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 18, "Chandraleela Hospital", "Private", "P-13 Uttam Nagar", "Delhi", 7947328870);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 19, "Pearl Hospital", "Private", "RZ-40 Block -A Najafgarh", "Delhi", 7947293349);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 20, "Mahavir Multispeciality Hospital", "Private", "K-4 12 A Mohan Garden", "Delhi", 7947214030);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 21, "Ashok Nursing Home & Multispeciality Hospital", "Private", "Near Vijay Chowk ", "Delhi", 7947223082);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 22, "Aastha Hospital", "Private", "L-2/50 Outer Ring Road ", "Delhi", 7947220111);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 23, "Cribs Hospital & Rmc Diagnostics", "Private", "Shaheen Bagh", "Delhi", 7947220745);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 24, "Lotus Hospital", "Private", "Janak Park-hari Nagar", "Delhi", 7947211538);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 25, "Shri Ram Singh Multispeciality Hospital", "Private", "Vikas Marg Sector 70 Noida", "Delhi", 7947241868);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 26, "Prasad Health Care", "Private", "Plot No 24 Sainik Enclave", "Delhi", 7947466954);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 27, "Samar Hospital", "Private", "Diary Dwarka Road", "Delhi", 7947461589);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 28, "Gandhi Hospital", "Private", "Om Vihar-uttam Nagar", "Delhi", 7947209670);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 29, "K D Hospital", "Private", "Sector 37 C Gurgaon", "Delhi", 7947190613);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 30, "Rathore IMT Hospital & Troma Center", "Private", "Sector 7 Village Bas Pusla ", "Delhi", 7947212105);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 31, "Aruna Asaf Ali Govt. Hospital", "Government", "Rajpur Road", "Delhi", 23965532);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 32, "Acharyaashree Bhikshu Hospital", "Government", "Moti Nagar", "Delhi", 25423057);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 33, "Attar Sain Jain Hospital", "Government", "Lawrence Road", "Delhi", 25423011);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 34, "Baba Saheb Ambedkar Hospital", "Government", "Sector 6 Rohini", "Delhi", 27034535);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 35, "Bhagwan Mahaveer Hospital", "Government", "Pitampura", "Delhi", 27055585);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 36, "Babu Jagjivan Ram Hospital", "Government", "Jahangir Puri", "Delhi", 27631810);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 37, "Chacha Nehru Bal Chikitsalaya", "Government", "Geeta Colony", "Delhi", 21210215);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 38, "Dadadev Mother & Child Hospital", "Government", "Nasirpur", "Delhi", 25395536);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 39, "Deen Dayal Upadhyay Hospital", "Government", "Hari Nagar", "Delhi", 25494337);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 40, "Deep Chand Bandhu Hospital", "Government", "Kokiwala Bagh", "Delhi", 27305953);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 41, "Delhi State Cancer Institution", "Government", "GTB Hospital Complex", "Delhi", 22110303);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 42, "Dr. Hedgewar Arogya Sansthan", "Government", "Karkardooma", "Delhi", 22393155);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 43, "Dr. N.C. Joshi Hospital", "Government", "Karol Bagh", "Delhi", 23611786);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 44, "Govind Ballabh Pant Hospital (G.B.P.H.)", "Government", "Jawahar Lal Nehru Marg", "Delhi", 23238109);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 45, "Guru Govind Singh Govt. Hospital", "Government", "Raghubir Nagar", "Delhi", 25984549);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 46, "Guru Nanak Eye Center", "Government", "Maharaja Ranjit Singh Marg", "Delhi", 23236931);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 47, "Guru Teg Bahadur Hospital (G.T.B.H.)", "Government", "Shahdara", "Delhi", 22581730);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 48, "Institute of Liver & Biliary Sciences (I.L.B.S.)", "Government", "Vasant Kunj", "Delhi", 46300000);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 49, "Janakpuri Super Speciality Hospital", "Government", "Janakpuri", "Delhi", 22112136);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 50, "Lal Bahadur Shastri Hospital (L.B.S.)", "Government", "Khichri Pur", "Delhi", 25552023);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 51, "Abhaya Hospital", "Private", "Park Area Wilson Garden", "Bangalore", 9874561210);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 52, "Bangalore Hospital", "Private", "South End Circle Jayanagar", "Bangalore", 9874561211);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 53, "Healthcare Global Enterprises (HCG)", "Private", "R R Mohan Roy Ext", "Bangalore", 9874561212);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 54, "Chaitanya Hospital", "Private", "Rt Nagar", "Bangalore", 9874561213);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 55, "Chord Road Hospital", "Private", "Basaveshawaranagar", "Bangalore", 9874561214);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 56, "Citi Hospital", "Private", "Rajajinagar", "Bangalore", 9874561215);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 57, "Hcg Koramangala", "Private", "Koramangala", "Bangalore", 9874561216);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 58, "Victoria Hospital", "Government ", "Fort Road", "Bangalore", 9874561217);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 59, "D G Hospital", "Private", "Padmanabhanagar", "Bangalore", 9874561218);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 60, "Rajiv Gandhi Institute of Chest Diseases", "Government ", "Kalyan Nagar", "Bangalore", 9874561219);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 61, "Gayathri Hospital Pvt Ltd", "Private", "Vijayanagar", "Bangalore", 9874561220);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 62, "Hosmat Hospital", "Private", " Off Richmond Road", "Bangalore", 9874561221);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 63, "Karthik Netralaya Institute Pvt Ltd", "Private", "Ashok Nagar", "Bangalore", 9874561222);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 64, "Koshys Hospital", "Private", "Tambuchetty Main Road", "Bangalore", 9874561223);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 65, "M S Ramaiah Hospitals", "Private", "M.S.R. Nagar", "Bangalore", 9874561224);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 66, "Mallya Hospital", "Private", "Vittal Mallya Road", "Bangalore", 9874561225);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 67, "Manipal Hospital", "Private", "Hal Airport Road", "Bangalore", 9874561226);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 68, "Manipal North Side Hospital", "Private", "Malleswaram", "Bangalore", 9874561227);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 69, "Manjushree Nursing Home Pvt Ltd", "Private", "St. Johns Road", "Bangalore", 9874561228);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 70, "Narayana Nethralaya", "Private", "Rajajinagar", "Bangalore", 9874561229);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 71, "Narayana Health", "Private", "Anekal Taluk", "Bangalore", 9874561230);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 72, "Nu Hospitals Pvt Ltd", "Private", "Padmanabhanagar", "Bangalore", 9874561231);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 73, "P D Hinduja Sindhi Hospital", "Private", "Sampangiramanagar", "Bangalore", 9874561232);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 74, "Panacea Hospitals Pvt Ltd", "Private", "Siddaiah Puranik Road", "Bangalore", 9874561233);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 75, "Prabha Hospital And Research Centre", "Private", "Jayanagar", "Bangalore", 9874561234);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 76, "Pristine Hospital And Research Centre Pvt Ltd", "Private", "Rajajinagar", "Bangalore", 9874561235);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 77, "Sagar Hospitals", "Private", "Jayanagar Extn", "Bangalore", 9874561236);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 78, "Sarojini Hospital", "Private", "Tumkur Road", "Bangalore", 9874561237);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 79, "Shaker Nursing Home", "Private", "Malleshwaram", "Bangalore", 9874561238);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 80, "Shirdi Sai Hospital Pvt Ltd", "Private", "New Bel Road", "Bangalore", 9874561239);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 81, "St Marthas Hospital", "Private", "Nrupatunga Road", "Bangalore", 9874561240);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 82, "Sudharsana Nethralaya", "Private", "Malleswaram", "Bangalore", 9874561241);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 83, "K C General Hospital", "Government", "Jayanagar", "Bangalore", 9874561242);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 84, "Indira Gandhi Institute of Child Health", "Government", "10th Main B.S.K. I Stage", "Bangalore", 9874561243);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 85, "Institute of Nephro Urology", "Government", "Link Road Malleswaram", "Bangalore", 9874561244);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 86, "Trinity Hospital And Heart Foundation", "Private", "Basavanagudi", "Bangalore", 9874561245);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 87, "Vijaya Nethralaya", "Private", "Ring Road", "Bangalore", 9874561246);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 88, "Vinayaka Hospital", "Private", "Hanumantha nagar", "Bangalore", 9874561247);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 89, "Vittala International Institute Of Ophthalmology", "Private", "2 Main Bsk 3 Stg", "Bangalore", 9874561248);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 90, "K K Hospital", "Private", "Yelahanka New Town", "Bangalore", 9874561249);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 91, "Nayak Hospital", "Private", "Gayathrinagar", "Bangalore", 9874561250);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 92, "Shekhar Hospital", "Private", "Jayanagar", "Bangalore", 9874561251);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 93, "Shreya Hospital", "Private", "Kengeri Satellite Town", "Bangalore", 9874561252);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 94, "Mediscope Hospital Pvt Ltd", "Private", "Iii Stage", "Bangalore", 9874561253);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 95, "Columbia Asia Medical Center", "Private", "Hebbal", "Bangalore", 9874561254);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 96, "Shekhar Hospital", "Private", "Bull Temple Road", "Bangalore", 9874561255);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 97, "Udhbhava Hospital", "Private", "Banashankari 3rd Stage", "Bangalore", 9874561256);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 98, "Lakshmi Hospital", "Private", "Judges Colony Ganganagar", "Bangalore", 9874561257);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 99, "Jayanagar General Hospital", "Government ", "Hosur Main Road", "Bangalore", 9874561258);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 100, "Neha Prakash Hospital", "Private", "Yelahanka New Town", "Bangalore", 9874561259);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 101, "R G Stone Urological Research Institute", "Private", "Mahavir Hospital Linking Road", "Mumbai", 9853146151);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 102, "Arpan Nursing Home & Iccu", "Government", "Kurla(West)", "Mumbai", 9853146152);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 103, "City Hospital & Research Centre", "Government", "Kurla(West)", "Mumbai", 9853146153);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 104, "Puranik Hospital", "Private", "Malad(W)", "Mumbai", 9853146154);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 105, "A-Care Orthopaedic & General Hospital", "Government", "Mira Road(E)", "Mumbai", 9853146155);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 106, "Ameya Surgical & General Nursing Home", "Private", "J.B.Nagar,Opp.Om Nagar", "Mumbai", 9853146156);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 107, "Apex Hospitals", "Private", "Borivali (West)", "Mumbai", 9853146157);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 108, "Arihant Heart Clinic", "Government", "Borivali (West)", "Mumbai", 9853146158);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 109, "Bses Mg Hospital ", "Government", "Andheri (W)", "Mumbai", 9853146159);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 110, "Dhanwantry Hospital & Iccu", "Private", "Mulund(W)", "Mumbai", 9853146160);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 111, "Gokul Hospital", "Government", "Kandivali(E)", "Mumbai", 9853146161);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 112, "Kokan Hospital", "Private", "Kokan Nagar", "Mumbai", 9853146162);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 113, "Pikale Hospital", "Private", "Mahim(W)", "Mumbai", 9853146163);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 114, "Riddhi Vinayak Critical Care", "Government", "Malad(W)", "Mumbai", 9853146164);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 115, "Shah Nursing Home", "Government", "Matunga", "Mumbai", 9853146165);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 116, "S.R.Mehta & Sir K.P Cardiac Institute", "Private", "King'S Circle", "Mumbai", 9853146166);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 117, "Smt.B.C.J. General Hospital", "Government", "Santacruz", "Mumbai", 9853146167);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 118, "Madhu Polyclinic & Nursing Home", "Private", "Bhandup(West)", "Mumbai", 9853146168);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 119, "S.A.S Health Care Pvt.Ltd", "Private", "Bhandup(W)", "Mumbai", 9853146169);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 120, "National Hospital", "Government", "Borivali (West)", "Mumbai", 9853146170);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 121, "Kolekar Nursing Home", "Government", "Chembur", "Mumbai", 9853146171);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 122, "Niramaya General Hospital", "Private", "Sion Trombay Rd", "Mumbai", 9853146172);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 123, "Punamiya Hospital", "Government", "Dadar West", "Mumbai", 9853146173);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 124, "Global hospital", "Private", "Parel", "Mumbai", 9853146174);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 125, "Tandon Hospital", "Private", "Near Ambedkar Garden", "Mumbai", 9853146175);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 126, "Thakur Hospital", "Government", "ShivajiPark", "Mumbai", 9853146176);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 127, "Savia's Polyclinic & Nursing Home", "Government", "Jeevdaya Lane Ghatkopar(W)", "Mumbai", 9853146177);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 128, "Satyam Hospital", "Private", "Ghatkopar(West)", "Mumbai", 9853146178);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 129, "Baliga Nursing Home", "Government", "Goregaon West", "Mumbai", 9853146179);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 130, "Fortis Hospital", "Private", "Murbad Road", "Mumbai", 9853146180);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 131, "Shivam Nursing Home", "Private", "Charkop Kandiwali(West)", "Mumbai", 9853146181);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 132, "Powai Polyclinic & Hospital", "Government", "Kanjur Marg Station", "Mumbai", 9853146182);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 133, "Iria Nursing Home & Polyclinic", "Government", "Vile Parle W", "Mumbai", 9853146183);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 134, "Apollo Hospital", "Private", "Kemp's Corner", "Mumbai", 9853146184);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 135, "Cumballa Hospital", "Government", "Kemps Corner", "Mumbai", 9853146185);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 136, "Sonagra Medical And Surgical Centre", "Private", "Ghatkopar(West)", "Mumbai", 9853146186);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 137, "Thunga Hospital", "Private", "Mira Road-East", "Mumbai", 9853146187);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 138, "Asian Heart Institute", "Government", "Bandra-Kurla Complex", "Mumbai", 9853146188);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 139, "Saifee Hospital", "Government", "Maharshi Karve Marg", "Mumbai", 9853146189);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 140, "Nupur Nursing Home", "Private", "Kandivali East", "Mumbai", 9853146190);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 141, "S.L.Raheja Hospital", "Government", "Mahim(West)", "Mumbai", 9853146191);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 142, "L H Hiranandani Hospital", "Private", "Powai", "Mumbai", 9853146192);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 143, "Bothra's Hospital", "Private", "Bhandup(W)", "Mumbai", 9853146193);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 144, "Ahuja Nursing Home", "Government", "Ulhasnagar", "Mumbai", 9853146194);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 145, "Fortis Hiranandani Hospital", "Government", "Navi Mumbai", "Mumbai", 9853146195);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 146, "Holy Spirit Hospital", "Private", "Andheri(E)", "Mumbai", 9853146196);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 147, "Jaslok Hospital", "Government", "Mahalaxmi", "Mumbai", 9853146197);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 148, "Lilavati Hospital", "Private", "Bandra(W)", "Mumbai", 9853146198);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 149, "Fortis Hospital Limited", "Private", "Mulund", "Mumbai", 9853146199);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 150, "Paramount General Hospital", "Government", "Sakinaka Junction", "Mumbai", 9853146200);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 151, "Narayana Multispeciality Hospital", "Private", "Jessore Road", "Kolkata", 8067506860);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 152, "Ruby General Hospital", "Private", "Anandapur Main Rd", "Kolkata", 9137516861);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 153, "Fortis Medical Centre", "Private", "Sarat Bose Rd", "Kolkata", 7067506462);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 154, "AMRI Hospital", "Private", "Bidhannagar", "Kolkata", 5037576863);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 155, "Calcutta Heart Clinic & Hospital", "Private", "Bidhannagar", "Kolkata", 8333506864);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 156, "Lions North Hospital", "Private", "Ranikuthi", "Kolkata", 6001198390);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 157, "Birla Heart Research", "Private", "Alipore", "Kolkata", 7067511461);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 158, "Calcutta Medical Institute", "Government", "Diamond Harbour Rd", "Kolkata", 9127523261);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 159, "Manipal Hospital", "Private", "193 Broadway Rd ", "Kolkata", 8112306860);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 160, "Humanity Hospital", "Private", "Hanspukur Road", "Kolkata", 9132616861);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 161, "Charnock Hospital", "Private", "Biswa Bangla Sarani", "Kolkata", 8067506861);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 162, "Calcutta National Medical College & Hospital", "Government", "Gorachand Rd", "Kolkata", 9137516862);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 163, "Miot Hospitals", "Private", "Kala Mandir", "Kolkata", 7067506463);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 164, "BSF Central Hospital", "Government", "Bidhannagar", "Kolkata", 5037576864);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 165, "Mission Of Mercy Hospital", "Private", "1 Park St", "Kolkata", 8333506865);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 166, "Global Hospitals", "Private", "Dev Lane", "Kolkata", 6001198396);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 167, "Apollo Multispeciality Hospitals", "Private", "Canal Circular Rd", "Kolkata", 7067511478);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 168, "Health Point Hospital", "Private", "Pandit Street", "Kolkata", 9127523260);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 169, "Ramkrishna Medical Complex", "Private", "Narkeldanga Rd", "Kolkata", 8112306869);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 170, "Calcutta Pavlov Hospital", "Government", "Gobra Rd", "Kolkata", 9132616863);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 171, "Rabindranath Tagore Institute", "Government", "Mukundpur", "Kolkata", 8121349902);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 172, "Remedy Hospital", "Private", "Garia Station", "Kolkata", 8121349903);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 173, "Command Hospital", "Private", "Alipore Rd", "Kolkata", 8121349904);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 174, "Assembly Of God Church Hospital", "Government", "Park St", "Kolkata", 8121349905);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 175, "BNR Hospital", "Private", "Garden Reach Rd", "Kolkata", 8121349906);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 176, "Eskag Sanjeevani Hospital", "Private", "Rahara Rd", "Kolkata", 8121349907);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 177, "Park Circus Hospital", "Government", "Beck Bagan Row", "Kolkata", 8121349908);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 178, "Rehmatbai Hospital", "Private", "Dharamtala", "Kolkata", 8121349909);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 179, "Sagore Dutt Hospital", "Government", "Kamarhati", "Kolkata", 8121349910);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 180, "J.B. Roy State Medical Hospital", "Government", "Raja Dinendra St", "Kolkata", 8121349911);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 181, "Goenka Hospital", "Private", "Muktaram Babu St", "Kolkata", 8121349912);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 182, "Echo Hospital", "Private", "New Town", "Kolkata", 8121349913);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 183, "Amrit Hospital", "Private", "Bhakuria", "Kolkata", 8121349914);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 184, "Narayana Superspeciality Hospital", "Private", "Howrah", "Kolkata", 8121349915);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 185, "North Suburban Hospital", "Private", "Lalbajar", "Kolkata", 8121349916);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 186, "Calcutta Medical College", "Government", "College Square", "Kolkata", 8121349917);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 187, "ESIC Medical College And Hospital", "Government", "Joka", "Kolkata", 8121349918);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 188, "Calcutta Unani Hospital", "Government", "Abdul Halim Lane", "Kolkata", 8121349919);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 189, "Kolkata Medical Center And Hospital", "Government", "Narkeldanga Rd", "Kolkata", 8121349920);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 190, "PEN Hospital", "Private", "Chowringee Rd", "Kolkata", 8121349921);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 191, "R G Kar Medical College And Hospital", "Government", "Shyambazar", "Kolkata", 8121349922);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 192, "Lady Dufferin Victoria Hospital", "Government", "Bowbazar", "Kolkata", 8121349923);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 193, "Shusrusha Nursing Home", "Private", "Banerjee Road", "Kolkata", 8121349924);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 194, "Olivia Nursing Home", "Private", "Jessore Road", "Kolkata", 8121349925);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 195, "Goodace Hospital", "Private", "Prafulla Kanan", "Kolkata", 8121349926);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 196, "Phoenix Hospital ", "Private", "Gupta Sarani Rd", "Kolkata", 8121349927);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 197, "Premananda Memorial Hospital", "Private", "Manicktala", "Kolkata", 8121349928);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 198, "Anandalok Hospital", "Private", "Salt Lake city", "Kolkata", 8121349929);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 199, "Ariyan Hospital Multispeciality", "Private", "Biswa Bangla Sarani", "Kolkata", 8121349930);
INSERT INTO HOSPITAL(REG_ID, NAME, OWNERSHIP, LOCATION, CITY, CONTACT ) VALUES( 200, "Columbia Asia Hospital", "Private", "Salt Lake city", "Kolkata", 8121349931);