-- #1 An Accident took place in Kolkata & there is an urgent need of O Negative Blood group,
-- Tell the best, 5 hospital available with bedS & oxygen.
USE COVID_RESOURCE_MANAGEMENT;
SELECT  NAME, LOCATION,CONTACT,BEDS,OXYGEN,MORTALITY_RATE FROM HOSPITAL,RESOURCES,COVID_STATUS,BLOOD_BANK 
WHERE 
HOSPITAL.REG_ID=RESOURCES.REG_ID AND
HOSPITAL.REG_ID=BLOOD_BANK.REG_ID AND
HOSPITAL.REG_ID=COVID_STATUS.REG_ID AND 
BLOOD_GROUP = "O Negative" AND
CITY ="Kolkata" AND BEDS <> 0 AND OXYGEN <> 0 AND 
NAME IN(SELECT NAME FROM COVID_STATUS ORDER BY MORTALITY_RATE ) ORDER BY MORTALITY_RATE LIMIT 5;

-- #2 DISPLAYING COVID STATUS OF FOUR CITY (Average Active Cases, Average Mortality Rate, Average Recovered)
SELECT CITY ,
ROUND(AVG( ACTIVE_CASES)) AS AVG_ACTIVE_CASES ,
CAST(AVG(MORTALITY_RATE) AS DECIMAL(5,2)) AS AVG_MORTALITY_RATE ,
ROUND(AVG(RECOVERED))  AS AVG_RECOVERED FROM 
HOSPITAL INNER JOIN COVID_STATUS  
ON HOSPITAL.REG_ID=COVID_STATUS.REG_ID 
GROUP BY CITY
ORDER BY  AVG_MORTALITY_RATE DESC;

-- #3 DISPLAYING COVID STATUS OF GOVT AND PRIVATE HOSPITAL
SELECT CITY,OWNERSHIP,
ROUND(SUM( ACTIVE_CASES) /COUNT(HOSPITAL.REG_ID)) AS AVG_ACTIVE_CASES ,
CAST(AVG(MORTALITY_RATE) AS DECIMAL(5,2)) AS AVG_MORTALITY_RATE ,
ROUND(SUM(RECOVERED) /COUNT(HOSPITAL.REG_ID)) AS AVG_RECOVERED ,
COUNT(OWNERSHIP) AS NO_OF_HOSPITALS FROM 
HOSPITAL INNER JOIN COVID_STATUS  
ON HOSPITAL.REG_ID=COVID_STATUS.REG_ID 
GROUP BY CITY,OWNERSHIP 
ORDER BY  CITY ;

-- #4  Comparing goverment and private hospitals ON BASE OF RESOURCES 
SELECT CITY,OWNERSHIP,
SUM(BEDS) AS TOTAL_BEDS,
SUM(OXYGEN) AS TOTAL_OXYGEN_CYLINDER,
SUM(REMDESIVIR) AS TOTAL_REMDESIVIR,
SUM(VENTILATOR) AS TOTAL_VENTILATOR FROM
HOSPITAL INNER JOIN RESOURCES
ON HOSPITAL.REG_ID=RESOURCES.REG_ID 
GROUP BY CITY,OWNERSHIP 
ORDER BY CITY DESC;

-- #5 Vaccination Status
SELECT CITY , DOSE_TYPE , count(*)  AS CENTERS
FROM HOSPITAL INNER JOIN VACCINATION
ON HOSPITAL.REG_ID=VACCINATION.REG_ID 
GROUP BY CITY , DOSE_TYPE 
ORDER BY CITY ;

-- #6 PROCEDURE for covid patient needs oxygen in A PARTICULAR CITY 
DELIMITER  $$
CREATE PROCEDURE NEED_OXYGEN( CITY_NAME VARCHAR(30))
BEGIN
		SELECT  NAME, LOCATION,CONTACT,OXYGEN FROM HOSPITAL
        INNER JOIN RESOURCES  ON HOSPITAL.REG_ID=RESOURCES.REG_ID 
        WHERE CITY = CITY_NAME AND BEDS >= 1 AND OXYGEN <> 0 
		ORDER BY OXYGEN DESC LIMIT 5 ;
END $$
DELIMITER ;
CALL NEED_OXYGEN("Kolkata") ;

-- #7 PROCEDURE for patient need BLOOD in CITY (CITY_NAME,BLOOD_GROUP)
DELIMITER  $$
CREATE PROCEDURE NEED_BLOOD( CITY_NAME VARCHAR(30) , BLOOD_G VARCHAR(15) )
BEGIN
		SELECT  NAME, LOCATION,OWNERSHIP  FROM   HOSPITAL 
        INNER JOIN BLOOD_BANK  ON HOSPITAL.REG_ID=BLOOD_BANK.REG_ID 
        WHERE CITY = CITY_NAME AND BLOOD_GROUP = BLOOD_G
		LIMIT 5 ;
END $$
DELIMITER ;
CALL NEED_BLOOD("Delhi" , "A POSITIVE");